### ISSUE TITLE
fetch Response.ok has not been implemented

### ISSUE THREAD

**Issue by ghostfuel** [SachaCR/denock#4]
Nearly there! My tests can nearly run and pass with Denock, however I'm relying on fetch's [Response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) to quickly decide if the response is an error or not. However, this doesn't exist on the mocked fetch response and so, fails.

Thanks again!

**Comment by SachaCR** [comment]
Thanks for your feedback I'll take a look at that as soon as I can.

**Comment by khrome83** [comment]
ping @ghostfuel, the new cut release supports it.
